# Ch02. (1유형) 결측값 처리

In [1]:
import pandas as pd

data = {
    '이름': ['철수', '영희', '민수', '선호'],
    '나이': [25, None, 30, 28],
    '성별': ['남', '여', '남', None]
}
df = pd.DataFrame(data)
df

   이름    나이    성별
0  철수  25.0     남
1  영희   NaN     여
2  민수  30.0     남
3  선호  28.0  None

In [ ]:
df.isnull()
#각 원소가 결측값인지를 Boolean으로 반환(null이면 true)

      이름     나이     성별
0  False  False  False
1  False   True  False
2  False  False  False
3  False  False   True

In [14]:
df.isnull().sum()
# 열 단위로 결측값 개수 집계
#df.isnull().sum().sum()
# 총 결측값 개수 집계

이름    0
나이    1
성별    1
dtype: int64

In [4]:
# 결측값을 원하는 값으로 채움(특정값/평균값/최빈값... 여기서는 특정값0)
df['나이'].fillna(0)

0    25.0
1     0.0
2    30.0
3    28.0
Name: 나이, dtype: float64

In [ ]:
# 나이의 평균값으로 결측값 대체
df['나이'].fillna(df['나이'].mean())

0    25.000000
1    27.666667
2    30.000000
3    28.000000
Name: 나이, dtype: float64

In [ ]:
# 나이의 평균값으로 결측값 대체
# mode함수: 최빈값을 Series 형태로 반환(최빈값이 여러 개일 수 있기 때문에)
df['성별'].fillna(df['성별'].mode()[0]) # [0]으로 인덱스 지정해줘야 함. -> 최빈값 중 첫값만 사용

0    남
1    여
2    남
3    남
Name: 성별, dtype: object

In [ ]:
df['성별'].mode()
# 최빈값이 한 개

0    남
Name: 성별, dtype: object

In [ ]:
# 이전 값으로 채우기 forward: 철수의 나이로
df.ffill()

   이름    나이 성별
0  철수  25.0  남
1  영희  25.0  여
2  민수  30.0  남
3  선호  28.0  남

In [9]:
# 다음 값으로 채우기 backward: 민수의 나이로
df.bfill()

   이름    나이    성별
0  철수  25.0     남
1  영희  30.0     여
2  민수  30.0     남
3  선호  28.0  None

In [ ]:
# 결측값 제거
# dropna(): 결측값 있는 전체 행 제거
df.dropna()
# 나이 결측 영희, 성별 결측 선호 제거

   이름    나이 성별
0  철수  25.0  남
2  민수  30.0  남

In [12]:
# dropna(subset=["열이름"]): 특정 열 기준으로 제거
df.dropna(subset=['성별'])
# 성별 결측 선호만 제거

   이름    나이 성별
0  철수  25.0  남
1  영희   NaN  여
2  민수  30.0  남