# Ch05. (1유형) 정렬

In [1]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve',
             'Frank', 'Grace', 'Hannah', 'Ian', 'Judy'],
    'Salary': [3200, 3400, 3100, 8000, 3300,
               3600, 9000, 3000, 3400, 9500],
    'Age': [25, 28, 26, 27, 29,
            30, 26, 31, 32, 28]
}
df = pd.DataFrame(data)
df

      Name  Salary  Age
0    Alice    3200   25
1      Bob    3400   28
2  Charlie    3100   26
3    David    8000   27
4      Eve    3300   29
5    Frank    3600   30
6    Grace    9000   26
7   Hannah    3000   31
8      Ian    3400   32
9     Judy    9500   28

In [3]:
# 단일 컬럼 정렬 sort_values
# by: 정렬 기준이 되는 컬럼명, 디폴트는 오름차순(ascending = True)

df.sort_values(by='Salary')

      Name  Salary  Age
7   Hannah    3000   31
2  Charlie    3100   26
0    Alice    3200   25
4      Eve    3300   29
1      Bob    3400   28
8      Ian    3400   32
5    Frank    3600   30
3    David    8000   27
6    Grace    9000   26
9     Judy    9500   28

In [ ]:
# 내림차순
df.sort_values(by='Age', ascending=False)

      Name  Salary  Age
8      Ian    3400   32
7   Hannah    3000   31
5    Frank    3600   30
4      Eve    3300   29
9     Judy    9500   28
1      Bob    3400   28
3    David    8000   27
2  Charlie    3100   26
6    Grace    9000   26
0    Alice    3200   25

In [5]:
# 다중 컬럼 기준 정렬
# 연봉 오름차순, 그 중에 같은 값이 있으면 그때 나이로 내림차순
df.sort_values(by=['Salary', 'Age'], ascending=[True, False])

      Name  Salary  Age
7   Hannah    3000   31
2  Charlie    3100   26
0    Alice    3200   25
4      Eve    3300   29
8      Ian    3400   32
1      Bob    3400   28
5    Frank    3600   30
3    David    8000   27
6    Grace    9000   26
9     Judy    9500   28

In [6]:
df = pd.DataFrame({'A': [3, 1, 2]})

# inplace=False (기본값)
new_df = df.sort_values(by='A')   # 정렬된 새 객체 반환
print(new_df)
print(df)                         # 원본은 그대로 유지

# inplace=True
df.sort_values(by='A', inplace=True)  # 원본 df 자체가 정렬됨
print(df)                             # 원본이 바뀜, 메서드는 None 반환

   A
1  1
2  2
0  3
   A
0  3
1  1
2  2
   A
1  1
2  2
0  3