# Ch08. (1유형) 피벗테이블

In [1]:
import pandas as pd

data = {
    'Department': ['Sales', 'Sales', 'HR', 'HR', 'Sales', 'IT', 'IT'],
    'Gender': ['M', 'F', 'M', 'F', 'M', 'M', 'F'],
    'Salary': [3000, 3200, 2500, 2700, 3100, 4000, 3900]
}

df = pd.DataFrame(data)
df

  Department Gender  Salary
0      Sales      M    3000
1      Sales      F    3200
2         HR      M    2500
3         HR      F    2700
4      Sales      M    3100
5         IT      M    4000
6         IT      F    3900

In [2]:
# 피벗테이블: 데이터를 요약(집계)하고 차원 축소하여 가독성 높은 형태로 재구성하는 도구
# 행 인덱스, 값을 지정해 집계함수(aggfunc)로 요약
# pd.pivot_table(index='column a', columns='column b', values='column c', aggfunc='mean')

pd.pivot_table(df, index='Department', values='Salary', aggfunc='mean')

            Salary
Department
HR          2600.0
IT          3950.0
Sales       3100.0

In [3]:
pd.pivot_table(df, index='Department', columns='Gender', values='Salary', aggfunc='mean')

Gender           F       M
Department
HR          2700.0  2500.0
IT          3900.0  4000.0
Sales       3200.0  3050.0

In [4]:
# 여러 집계 함수를 리스트로 활용

pd.pivot_table(df, index='Department', values='Salary',
               aggfunc=['mean', 'max', 'min'])

              mean    max    min
            Salary Salary Salary
Department
HR          2600.0   2700   2500
IT          3950.0   4000   3900
Sales       3100.0   3200   3000

In [5]:
pivot = pd.pivot_table(df, index='Department', columns='Gender',
                       values='Salary', aggfunc='mean')
pivot

Gender           F       M
Department
HR          2700.0  2500.0
IT          3900.0  4000.0
Sales       3200.0  3050.0

In [6]:
# stack(): wide -> long
# unstack(): long -> wide

pivot1 = pivot.stack()
pivot1

Department  Gender
HR          F         2700.0
            M         2500.0
IT          F         3900.0
            M         4000.0
Sales       F         3200.0
            M         3050.0
dtype: float64

In [7]:
pivot2 = pivot1.unstack()
pivot2

Gender           F       M
Department
HR          2700.0  2500.0
IT          3900.0  4000.0
Sales       3200.0  3050.0