# Ch06. (1유형) 내장함수

In [1]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Department': ['Sales', 'HR', 'Sales', 'HR', 'Sales'],
    'Gender': ['F', 'M', 'M', 'M', 'F'],
    'Age': [25, 30, 45, 28, 35],
    'Salary': [3000, 3200, 3400, 3100, 3300]
}

df = pd.DataFrame(data)
df

# 내장함수: 데이터를 정리/요약하여 구조를 변형
# -> 실기에서는 단독 or 조합 문제 출제

      Name Department Gender  Age  Salary
0    Alice      Sales      F   25    3000
1      Bob         HR      M   30    3200
2  Charlie      Sales      M   45    3400
3    David         HR      M   28    3100
4      Eve      Sales      F   35    3300

In [2]:
# unique(): 해당 열에서 중복 제거한 고유값 배열 반환

df['Department'].unique()

array(['Sales', 'HR'], dtype=object)

In [3]:
# value_counts(): 빈도 수 반환
df['Department'].value_counts()

Department
Sales    3
HR       2
Name: count, dtype: int64

In [4]:
# 사용자 정의 함수 

def classify_age(row):
    if row['Age'] < 30:
        return '청년'
    else:
        return '장년'

In [7]:
# apply(): 사용자 정의 함수 적용
# axis=0: 열 방향 처리 -> 행 단위 적용
# axis=1: 행 방향 처리 -> 열 단위 적용

df['Age_Group'] = df.apply(classify_age, axis=1)
df

      Name Department Gender  Age  Salary Age_Group
0    Alice      Sales      F   25    3000        청년
1      Bob         HR      M   30    3200        장년
2  Charlie      Sales      M   45    3400        장년
3    David         HR      M   28    3100        청년
4      Eve      Sales      F   35    3300        장년

In [11]:
df2 = pd.DataFrame({
    'Name': ['Alice', 'Bob'],
    'Math': [90, 85],
    'English': [88, 92],
    'History': [92, 82]
})
df2

    Name  Math  English  History
0  Alice    90       88       92
1    Bob    85       92       82

In [13]:
# melt(): Wide -> Long 형태로 변환

pd.melt(df2, id_vars='Name',  value_vars=['Math', 'English','History'],
        var_name='Subject', value_name='Score')

    Name  Subject  Score
0  Alice     Math     90
1    Bob     Math     85
2  Alice  English     88
3    Bob  English     92
4  Alice  History     92
5    Bob  History     82