# Ch04. (1유형) 표준화와 정규화

In [1]:
# 정규화(Normalization): 데이터의 값을 0~1 범위로 압축하여 동일한 스케일로 맞추는 작업
# 표준화(Standardization):  데이터의 값을 평균이 0, 표준편차가 1이 되도록 변환하는 기법

import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve',
             'Frank', 'Grace', 'Hannah', 'Ian', 'Judy'],
    'Salary': [3200, 3400, 3100, 8000, 3300,
               3600, 9000, 3000, 3400, 9500],
    'Age': [25, 28, 26, 27, 29,
            30, 26, 31, 32, 28]
}

df = pd.DataFrame(data)
df

      Name  Salary  Age
0    Alice    3200   25
1      Bob    3400   28
2  Charlie    3100   26
3    David    8000   27
4      Eve    3300   29
5    Frank    3600   30
6    Grace    9000   26
7   Hannah    3000   31
8      Ian    3400   32
9     Judy    9500   28

In [2]:
# Min-Max 정규화
df['정규화'] = (df['Salary'] - df['Salary'].min()) / (df['Salary'].max() - df['Salary'].min())

# Z-score 표준화
df['표준화'] = (df['Salary'] - df['Salary'].mean()) / df['Salary'].std()

df

      Name  Salary  Age       정규화       표준화
0    Alice    3200   25  0.030769 -0.646010
1      Bob    3400   28  0.061538 -0.572180
2  Charlie    3100   26  0.015385 -0.682925
3    David    8000   27  0.769231  1.125903
4      Eve    3300   29  0.046154 -0.609095
5    Frank    3600   30  0.092308 -0.498351
6    Grace    9000   26  0.923077  1.495052
7   Hannah    3000   31  0.000000 -0.719840
8      Ian    3400   32  0.061538 -0.572180
9     Judy    9500   28  1.000000  1.679626

In [6]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
# 정규화/표준화를 일일이 계산하지 않고 fit_transform으로 바로 적용
# 2차원 형태로 넣어야 함 [['Salary']]

# 예시 데이터
df = pd.DataFrame({'Salary': [1000, 2000, 3000, 4000, 5000]})

# 정규화
scaler_minmax = MinMaxScaler()
df['정규화'] = scaler_minmax.fit_transform(df[['Salary']])

# 표준화
scaler_standard = StandardScaler()
# df['표준화'] = scaler_standard.fit_transform(df[['Salary']])
df['표준화'] = scaler_standard.fit(df[['Salary']])
df['표준화'] = scaler_standard.transform(df[['Salary']])


df

   Salary   정규화       표준화
0    1000  0.00 -1.414214
1    2000  0.25 -0.707107
2    3000  0.50  0.000000
3    4000  0.75  0.707107
4    5000  1.00  1.414214