# Ch10. (1유형) 날짜/시간 데이터 처리

In [ ]:

# 날짜/시간 데이터(datetime): 단순 문자열x, 연산/비교/추출이 가능한 시간 정보 객체
# datetime 자료형으로 변환해야 다양한 분석/가공 가능

import pandas as pd

# 현재 시스템은 문자열 객체로 인식 중
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Date1': ['2024-04-20', '2023-07-11', '2021-11-09', '2023-03-29', '2024-12-12'],
    'Date2' : ['20/04/2024', '11/07/2023', '09/11/2021', '29/03/2023', '12/12/2024'],
    'Date3' : ['24:04:20', '23:07:11', '21:11:09', '23:03:29', '24:12:12']
}
df = pd.DataFrame(data)
df

      Name       Date1       Date2     Date3
0    Alice  2024-04-20  20/04/2024  24:04:20
1      Bob  2023-07-11  11/07/2023  23:07:11
2  Charlie  2021-11-09  09/11/2021  21:11:09
3    David  2023-03-29  29/03/2023  23:03:29
4      Eve  2024-12-12  12/12/2024  24:12:12

In [2]:
df.info()
# 일반적인 문자열은 object 데이터 타입

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Date1   5 non-null      object
 2   Date2   5 non-null      object
 3   Date3   5 non-null      object
dtypes: object(4)
memory usage: 292.0+ bytes

In [5]:
# pd.to_datetime(): 문자열을 날짜형으로 변환

df['Date1'] = pd.to_datetime(df['Date1'])
df['Date2'] = pd.to_datetime(df['Date2'])
# df['Date3'] = pd.to_datetime(df['Date3'])

# Date3은 포맷이 애매... 해서 자동인식 못하고 에러 발생

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Date1   5 non-null      datetime64[ns]
 2   Date2   5 non-null      datetime64[ns]
 3   Date3   5 non-null      object
dtypes: datetime64[ns](2), object(2)
memory usage: 292.0+ bytes

In [9]:
# format=옵션: 명시적으로 날짜 형식을 지정
# %y는 연도 2자리(26), %Y면 4자리 연도(2026)
# %H/M/S: 시간(00~23), 분, 초

df['Date3'] = pd.to_datetime(df['Date3'], format="%y:%m:%d")
df

      Name      Date1      Date2      Date3
0    Alice 2024-04-20 2024-04-20 2024-04-20
1      Bob 2023-07-11 2023-07-11 2023-07-11
2  Charlie 2021-11-09 2021-11-09 2021-11-09
3    David 2023-03-29 2023-03-29 2023-03-29
4      Eve 2024-12-12 2024-12-12 2024-12-12

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Date1   5 non-null      datetime64[ns]
 2   Date2   5 non-null      datetime64[ns]
 3   Date3   5 non-null      datetime64[ns]
dtypes: datetime64[ns](3), object(1)
memory usage: 292.0+ bytes

In [10]:
# dt 속성으로 날짜 정보 추출(datetime 포맷이어야 가능, 문자열 x)
# day_name은 요일 추출

df['Year'] = df['Date1'].dt.year
df['Month'] = df['Date1'].dt.month
df['Weekday'] = df['Date1'].dt.day_name()
df

      Name      Date1      Date2      Date3  Year  Month    Weekday
0    Alice 2024-04-20 2024-04-20 2024-04-20  2024      4   Saturday
1      Bob 2023-07-11 2023-07-11 2023-07-11  2023      7    Tuesday
2  Charlie 2021-11-09 2021-11-09 2021-11-09  2021     11    Tuesday
3    David 2023-03-29 2023-03-29 2023-03-29  2023      3  Wednesday
4      Eve 2024-12-12 2024-12-12 2024-12-12  2024     12   Thursday

In [ ]:
# timestamp로 오늘 날짜 지정
# df의 날짜들과의 날짜 차이 계산 가능(오늘로부터 경과일 수)

today = pd.Timestamp('2025-07-30')
df['Days Since'] = (today - df['Date1']).dt.days
df

,Name,Date1,Date2,Date3,Year,Month,Weekday,Days Since
0,Alice,2024-04-20,2024-04-20,2024-04-20,2024,4,Saturday,466
1,Bob,2023-07-11,2023-07-11,2023-07-11,2023,7,Tuesday,750
2,Charlie,2021-11-09,2021-11-09,2021-11-09,2021,11,Tuesday,1359
3,David,2023-03-29,2023-03-29,2023-03-29,2023,3,Wednesday,854
4,Eve,2024-12-12,2024-12-12,2024-12-12,2024,12,Thursday,230

In [ ]:
# 시간 반올림 주의: 시간 데이터를 평균 등으로 계산할 경우, 소수점 단위는 "분"이 아닌 "시간의 일부"
# 30.45분 -> 30분 27초(0.45 * 60 = 27)...45초 아님 주의!!

# 시간 차이 계산 주의: datetime 간 차이는 timedelta객체로 반환, 이 객체를 바로 나누면 에러 발생

time_avg_min = 30.45
minutes = int(time_avg_min)
seconds = round((time_avg_min - minutes) * 60)

print(f"{minutes}분 {seconds}초")

30분 27초

In [14]:
import pandas as pd

df = pd.DataFrame({
    'Start': ['2024-01-01 08:00:00', '2024-01-01 09:10:00'],
    'End':   ['2024-01-01 08:45:00', '2024-01-01 10:00:00']
})

df['Start'] = pd.to_datetime(df['Start'])
df['End'] = pd.to_datetime(df['End'])

# 반드시 dt.total_seconds()로 변환 후 60으로 나누어 분 단위로 변환하기
df['Duration_Minutes'] = (df['End'] - df['Start']).dt.total_seconds() / 60
df

                Start                 End  Duration_Minutes
0 2024-01-01 08:00:00 2024-01-01 08:45:00              45.0
1 2024-01-01 09:10:00 2024-01-01 10:00:00              50.0