# Ch07. DataFrame 수정과 삭제

In [2]:
import pandas as pd

data = {
    "이름" : ["철수", "영희"],
    "국어" : [90, 80],
    "수학" : [85, 95]
}
df = pd.DataFrame(data)
df.set_index("이름", inplace=True)
df

    국어  수학
이름
철수  90  85
영희  80  95

In [3]:
df["영어"] = 0
df

    국어  수학  영어
이름
철수  90  85   0
영희  80  95   0

In [4]:
df.loc['철수', '영어'] = 80
df

    국어  수학  영어
이름
철수  90  85  80
영희  80  95   0

In [5]:
# 행 값 변경

# df.loc["행 이름", "열 이름0" : "열 이름n"] = 값
# df.iloc["행 인덱스", "열 인덱스0" : "열 인덱스n+1"] = 값


df.iloc[1, 2] = 100
df

    국어  수학   영어
이름
철수  90  85   80
영희  80  95  100

In [6]:
data = {
    "이름" : ["철수", "영희", "민수", "지은"],
    "국어" : [90, 80, 0, 0],
    "수학" : [85, 95, 0, 0],
    "영어" : [80, 100, 0, 0]
}
df = pd.DataFrame(data)
df.set_index("이름", inplace=True)
df

    국어  수학   영어
이름
철수  90  85   80
영희  80  95  100
민수   0   0    0
지은   0   0    0

In [ ]:
# loc 슬라이스는 : 끝 값 포함

df.loc['민수', '국어':'영어'] = 85, 88, 75
df

    국어  수학   영어
이름
철수  90  85   80
영희  80  95  100
민수  85  88   75
지은   0   0    0

In [ ]:
# iloc 슬라이싱은 : 끝 값 미포함

df.iloc[3, 0:3] = 100, 95, 90
df

     국어  수학   영어
이름
철수   90  85   80
영희   80  95  100
민수   85  88   75
지은  100  95   90

In [14]:
data = {
    "이름" : ["철수", "영희", "민수", "지은"],
    "국어" : [90, 80, 85, 100],
    "수학" : [85, 95, 88, 95],
    "영어" : [80, 100, 75, 90]
}
df = pd.DataFrame(data)
df.set_index("이름", inplace=True)
df

     국어  수학   영어
이름
철수   90  85   80
영희   80  95  100
민수   85  88   75
지은  100  95   90

In [15]:
# 행 삭제(axis=0)
# inplace=True면 원본데이터에서 바로 반영, False면 삭제된 객체 반환(df= df.drop해야 반영됨)

df.drop('지은', axis=0, inplace=True)
df

    국어  수학   영어
이름
철수  90  85   80
영희  80  95  100
민수  85  88   75

In [ ]:
# 리스트로 여러 행 삭제
df.drop(['영희', '민수'], axis=0, inplace=True)
df

    국어  수학  영어
이름
철수  90  85  80

In [17]:
data = {
    "이름" : ["철수", "영희", "민수", "지은"],
    "국어" : [90, 80, 85, 100],
    "수학" : [85, 95, 88, 95],
    "영어" : [80, 100, 75, 90]
}
df = pd.DataFrame(data)
df.set_index("이름", inplace=True)
df

     국어  수학   영어
이름
철수   90  85   80
영희   80  95  100
민수   85  88   75
지은  100  95   90

In [ ]:
# 열 삭제(axis=1)

df_new = df.drop("수학", axis=1)
df_new

     국어   영어
이름
철수   90   80
영희   80  100
민수   85   75
지은  100   90

In [ ]:
df_new = df.drop(["국어", "수학"], axis=1)
df_new

     영어
이름
철수   80
영희  100
민수   75
지은   90

In [ ]:
df = pd.DataFrame({'A': [1, 2, 3]})

# inplace=False (기본)
new_df = df.drop([0])   # 0번째 행 삭제된 새 객체 반환
print(new_df)
print(df)               # 원본은 변하지 않음

# inplace=True
df.drop([0], inplace=True)  # 원본 df에서 0번째 행 삭제
print(df)                   # 원본이 변경됨

   A
1  2
2  3
   A
0  1
1  2
2  3
   A
1  2
2  3