# Ch06. 인덱스 선택

In [ ]:
import pandas as pd
df = pd.read_csv('coin.csv')
df

# pandas 기본 인덱스: 0,1,2 ... 숫자

           Date    Open    High     Low   Close
0    2017-03-01  25,534  26,446  25,222  26,382
1    2017-03-02  24,941  25,471  24,801  25,439
2    2017-03-03  25,860  26,044  24,900  24,941
3    2017-03-04  25,886  26,343  25,742  25,860
4    2017-03-05  26,135  26,151  25,677  25,886
..          ...     ...     ...     ...     ...
361  2018-02-25  20,501  20,940  19,840  20,444
362  2018-02-26  17,727  20,635  17,727  20,501
363  2018-02-27  20,618  20,723  17,630  17,727
364  2018-02-28  20,683  21,268  20,219  20,627
365  2018-03-01  21,693  22,899  20,522  20,683

[366 rows x 5 columns]

In [ ]:
# Date를 인덱스로 설정(df= df~~ 해서 넣어줘야 원본 데이터에 반영)

df = df.set_index('Date')
# ~~~read_csv(~~~, index_col=0)
df

              Open    High     Low   Close
Date
2017-03-01  25,534  26,446  25,222  26,382
2017-03-02  24,941  25,471  24,801  25,439
2017-03-03  25,860  26,044  24,900  24,941
2017-03-04  25,886  26,343  25,742  25,860
2017-03-05  26,135  26,151  25,677  25,886
...            ...     ...     ...     ...
2018-02-25  20,501  20,940  19,840  20,444
2018-02-26  17,727  20,635  17,727  20,501
2018-02-27  20,618  20,723  17,630  17,727
2018-02-28  20,683  21,268  20,219  20,627
2018-03-01  21,693  22,899  20,522  20,683

[366 rows x 4 columns]

In [5]:
print("-----특정 인덱스----")
print(df.loc['2018-01-01'])         # 인덱스가 날짜인 경우

print("-----인덱스 범위----")
print(df.loc[:, ['Open']])          # 열 선택

print("-----특정 행, 열----")
print(df.loc['2018-01-01', 'Open']) # 특정 행, 열

-----특정 인덱스----
Open     24,505
High     24,992
Low      24,178
Close    24,327
Name: 2018-01-01, dtype: object
-----인덱스 범위----
              Open
Date
2017-03-01  25,534
2017-03-02  24,941
2017-03-03  25,860
2017-03-04  25,886
2017-03-05  26,135
...            ...
2018-02-25  20,501
2018-02-26  17,727
2018-02-27  20,618
2018-02-28  20,683
2018-03-01  21,693

[366 rows x 1 columns]
-----특정 행, 열----
24,505

In [6]:
# 기존 loc는 라벨명 설정
# iloc는 숫자 인덱스로

print("-----특정 인덱스----")
print(df.iloc[0])            # 0 번째 행

print("-----인덱스 범위----")
print(df.iloc[:, [1, 2]])      # 1 번째, 2 번째 열

print("-----특정 행, 열----")
print(df.iloc[0, 1])           # 0 번째 행, 1 번째 열

-----특정 인덱스----
Open     25,534
High     26,446
Low      25,222
Close    26,382
Name: 2017-03-01, dtype: object
-----인덱스 범위----
              High     Low
Date
2017-03-01  26,446  25,222
2017-03-02  25,471  24,801
2017-03-03  26,044  24,900
2017-03-04  26,343  25,742
2017-03-05  26,151  25,677
...            ...     ...
2018-02-25  20,940  19,840
2018-02-26  20,635  17,727
2018-02-27  20,723  17,630
2018-02-28  21,268  20,219
2018-03-01  22,899  20,522

[366 rows x 2 columns]
-----특정 행, 열----
26,446

In [7]:
data = {'이름' : ['영희', '철수'],
        '나이' : [20, 22],
        '성별' : ['여', '남'],
        '점수' : [95, 90]}
df = pd.DataFrame(data)
df

   이름  나이 성별  점수
0  영희  20  여  95
1  철수  22  남  90

In [8]:
# inplace=True이면 원본데이터를 직접 변경(앞에 df= 으로 넣어주지 않아도)

df.set_index('이름', inplace=True)
df

    나이 성별  점수
이름
영희  20  여  95
철수  22  남  90

In [9]:
print(df.loc['영희',['성별','점수']])
print(df.iloc[0, [1, 2]])
print(df.loc['영희', '성별' : '점수'])
print(df.iloc[0, 1:])

성별     여
점수    95
Name: 영희, dtype: object
성별     여
점수    95
Name: 영희, dtype: object
성별     여
점수    95
Name: 영희, dtype: object
성별     여
점수    95
Name: 영희, dtype: object

In [10]:
data = {'이름' : ['영희', '철수'],
        '나이' : [20, 22],
        '성별' : ['여', '남'],
        '점수' : [95, 90]}
df = pd.DataFrame(data)
df.set_index('이름', inplace=True)
df

    나이 성별  점수
이름
영희  20  여  95
철수  22  남  90

In [11]:
#1. loc : 슬라이싱 끝 포함
print(df.loc['영희', '성별' : '점수'])

#2. iloc : 슬라이싱 끝 미포함
print(df.iloc[0, 1:2])

성별     여
점수    95
Name: 영희, dtype: object
성별    여
Name: 영희, dtype: object

In [12]:
data = {'이름' : ['영희', '철수'],
        '나이' : [20, 22],
        '성별' : ['여', '남'],
        '점수' : [95, 90]}
df = pd.DataFrame(data)
df.set_index('이름', inplace=True)
df

    나이 성별  점수
이름
영희  20  여  95
철수  22  남  90

In [ ]:
df['성별']

# 인덱스와 선택된 칼럽값을 조회

이름
영희    여
철수    남
Name: 성별, dtype: object

In [ ]:
# 두 개 이상의 열 선택: 열이름 리스트 필요
df[['나이','점수']]

    나이  점수
이름
영희  20  95
철수  22  90