# Ch09. DataFrame 병합

In [1]:
import pandas as pd

df1 = pd.DataFrame({'이름': ['영희', '철수'], '점수': [90, 85]})
df2 = pd.DataFrame({'이름': ['민수', '지영'], '점수': [88, 92]})

print(df1)
print(df2)

   이름  점수
0  영희  90
1  철수  85
   이름  점수
0  민수  88
1  지영  92

In [ ]:
# concat 함수: 데이터프레임 병합(행 병합은 axis=0, 열 병합은 axis=1)
# axis 옵션은 항상 0이 기본값

result1 = pd.concat([df1, df2])
print(result1)

   이름  점수
0  영희  90
1  철수  85
0  민수  88
1  지영  92

In [4]:
df3 = pd.DataFrame({'성별': ['여', '남']})
result = pd.concat([df1, df3], axis=1)
print(result)

   이름  점수 성별
0  영희  90  여
1  철수  85  남

In [5]:
# 병합 후 인덱스를 0부터 재설정

pd.concat([df1, df2], ignore_index=True)

   이름  점수
0  영희  90
1  철수  85
2  민수  88
3  지영  92

In [6]:
# keys : 계층적 인덱스 추가

pd.concat([df1, df2], keys=['상반기', '하반기'])

       이름  점수
상반기 0  영희  90
    1  철수  85
하반기 0  민수  88
    1  지영  92