# Ch08. 데이터 필터링

In [1]:
import pandas as pd
data = {
    "이름" : ["철수", "영희", "민수", "지은"],
    "국어" : [90, 80, 85, 100],
    "수학" : [85, 95, 88, 100],
    "영어" : [80, 100, 75, 90]
}
df = pd.DataFrame(data)
df.set_index("이름", inplace=True)
df

     국어   수학   영어
이름
철수   90   85   80
영희   80   95  100
민수   85   88   75
지은  100  100   90

In [3]:
# Boolean 인덱싱: 조건식 < > == != 등을 적용해 true/false 반환

df['국어'] > 85

이름
철수     True
영희    False
민수    False
지은     True
Name: 국어, dtype: bool

In [4]:
df[df['국어'] > 85]

     국어   수학  영어
이름
철수   90   85  80
지은  100  100  90

In [5]:
cond1 = df['국어'] > 85
cond2 = df['영어'] > 85

In [ ]:
# 조건 조합: 합집합/교집합을 활용해 2개 이상의 조건 조합
# 교집합 &: 둘 다 참이어야 참 

df[cond1 & cond2]

     국어   수학  영어
이름
지은  100  100  90

In [7]:
# 합집합 |: 하나만 참이어도 참

df[cond1 | cond2]

     국어   수학   영어
이름
철수   90   85   80
영희   80   95  100
지은  100  100   90

In [8]:
# 특정 목록에 포함되는 값만 필터링

cond = df['수학'].isin([100, 95])
df[cond]

     국어   수학   영어
이름
영희   80   95  100
지은  100  100   90

In [9]:
score = [100, 95]
cond = df['수학'].isin(score)
df[cond]

     국어   수학   영어
이름
영희   80   95  100
지은  100  100   90