# Ch05. DataFrame 열/행 추가

In [ ]:
import pandas as pd
df = pd.read_csv('countries.csv', index_col=0)
# 0번째 칼럼(국가 약자)을 인덱스로 지정
df

    country      area     capital  population
KR    Korea     98480       Seoul    51780579
US      USA   9629091  Washington   331002825
JP    Japan    377835       Tokyo   125960000
CN    China   9596960     Beijing  1439323688
RU   Russia  17100000      Moscow   146748600
DE  Germany    357022      Berlin    83200000

In [3]:
df['density']=0
# 새로운 칼럼 생성
df

    country      area     capital  population  density
KR    Korea     98480       Seoul    51780579        0
US      USA   9629091  Washington   331002825        0
JP    Japan    377835       Tokyo   125960000        0
CN    China   9596960     Beijing  1439323688        0
RU   Russia  17100000      Moscow   146748600        0
DE  Germany    357022      Berlin    83200000        0

In [4]:
df2 = pd.read_csv('countries.csv', index_col=0)

# 열에 통째로 접근해 여러 행을 한 번에 계산 -> 인구밀도 = 인구/면적
df2['density'] = df2['population'] / df2['area']
df2

    country      area     capital  population     density
KR    Korea     98480       Seoul    51780579  525.797918
US      USA   9629091  Washington   331002825   34.375293
JP    Japan    377835       Tokyo   125960000  333.373033
CN    China   9596960     Beijing  1439323688  149.977044
RU   Russia  17100000      Moscow   146748600    8.581789
DE  Germany    357022      Berlin    83200000  233.038860

In [5]:
data = {'이름' : ['영희', '철수'],
        '나이' : [20, 22],
        '성별' : ['여', '남'],
        '점수' : [95, 90]}
df = pd.DataFrame(data)
df

   이름  나이 성별  점수
0  영희  20  여  95
1  철수  22  남  90

In [6]:
# 새로운 행 추가 : loc(location)... 2번 행 추가
df.loc[2] = 0
df

   이름  나이 성별  점수
0  영희  20  여  95
1  철수  22  남  90
2   0   0  0   0

In [ ]:
# 각 칼럼마다 값을 리스트로 부여
# 기존에 값 있을 경우 덮어쓰기
df.loc[3] = ['민호', 21, '남', 50]
df

   이름  나이 성별  점수
0  영희  20  여  95
1  철수  22  남  90
2   0   0  0   0
3  민호  21  남  50

In [ ]:
# 백업 라벨로 행 추가(행 추가 시 인덱스명 지정 가능)

df.loc['백업'] = df.loc[1]
df

    이름  나이 성별  점수
0   영희  20  여  95
1   철수  22  남  90
2    0   0  0   0
3   민호  21  남  50
백업  철수  22  남  90