# Ch04. DataFrame 기초

In [1]:
import pandas as pd
df = pd.read_csv('countries.csv', index_col=0)
df

    country      area     capital  population
KR    Korea     98480       Seoul    51780579
US      USA   9629091  Washington   331002825
JP    Japan    377835       Tokyo   125960000
CN    China   9596960     Beijing  1439323688
RU   Russia  17100000      Moscow   146748600
DE  Germany    357022      Berlin    83200000

In [2]:
df.head()

   country      area     capital  population
KR   Korea     98480       Seoul    51780579
US     USA   9629091  Washington   331002825
JP   Japan    377835       Tokyo   125960000
CN   China   9596960     Beijing  1439323688
RU  Russia  17100000      Moscow   146748600

In [3]:
df.tail()

    country      area     capital  population
US      USA   9629091  Washington   331002825
JP    Japan    377835       Tokyo   125960000
CN    China   9596960     Beijing  1439323688
RU   Russia  17100000      Moscow   146748600
DE  Germany    357022      Berlin    83200000

In [4]:
df[:3]
# df[start: end+1]
# 인자 생략 시 처음부터 or 끝까지

   country     area     capital  population
KR   Korea    98480       Seoul    51780579
US     USA  9629091  Washington   331002825
JP   Japan   377835       Tokyo   125960000

In [5]:
df['population'][:3]
# 특정 컬럼 지정(컬럼명)

KR     51780579
US    331002825
JP    125960000
Name: population, dtype: int64

In [6]:
df.loc['KR']
# location의 약자, 특정 행/열의 라벨을 통해 지정

country          Korea
area             98480
capital          Seoul
population    51780579
Name: KR, dtype: object

In [7]:
df.loc['JP', 'capital']

'Tokyo'

In [8]:
df['capital'].loc['JP']

'Tokyo'

In [9]:
weather = pd.read_csv('weather.csv')
weather.describe()
# 데이터의 주요 통계 요약 정보 확인

          MinTemp     MaxTemp    Rainfall  WindGustSpeed
count  366.000000  366.000000  366.000000     364.000000
mean     7.265574   20.550273    1.428415      39.840659
std      6.025800    6.690516    4.225800      13.059807
min     -5.300000    7.600000    0.000000      13.000000
25%      2.300000   15.025000    0.000000      31.000000
50%      7.450000   19.650000    0.000000      39.000000
75%     12.500000   25.500000    0.200000      46.000000
max     20.900000   35.800000   39.800000      98.000000

In [ ]:
# 집계 함수

# 1. mean() - 평균의 반환
print(weather.mean())
# 2. std() - 표준편차의 반환
print(weather.std())

MinTemp           7.265574
MaxTemp          20.550273
Rainfall          1.428415
WindGustSpeed    39.840659
dtype: float64
MinTemp           6.025800
MaxTemp           6.690516
Rainfall          4.225800
WindGustSpeed    13.059807
dtype: float64

In [11]:
import numpy as np

In [12]:
# 두 표준편차의 차이
# ddof : delta degree of freedom(자유도 얼마나)

# 1. 넘파이 표준편차
data = [1, 2, 3, 4, 5]
print("Numpy 모집단 표준편차:", np.std(data))         # 기본적으로 모집단 표준편차(ddof=0)... n으로 나눈 값
print("Numpy 표본 표준편차:", np.std(data, ddof=1))   # ddof=1로 표본 표준편차

# 2. 판다스 표준편차
df = pd.DataFrame({'values': [1, 2, 3, 4, 5]})
print("Pandas 모집단 표준편차:", df['values'].std(ddof=0))  # ddof=0으로 모집단 표준편차
print("Pandas 표본 표준편차:", df['values'].std())          # 기본적으로 표본 표준편차(ddof=1)... n-1로 나눈 값

Numpy 모집단 표준편차: 1.4142135623730951
Numpy 표본 표준편차: 1.5811388300841898
Pandas 모집단 표준편차: 1.4142135623730951
Pandas 표본 표준편차: 1.5811388300841898